spring:
  datasource:
    url: jdbc:postgresql://localhost/sip_2
    username: beehive_tech
    password: beeisgood
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

auth:
  hash:
    seed: 48DkxzVnME4RSJXqcmOzGfNdXZZiYlTXLPVdV
  token:
    expiredInDays: 14

logging:
  level:
     org:
       springframework:
         security: DEBUG




